In [1]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd

#col_Names=["Class", "AGE", "SEX", "STEROID","ANTIVIRALS", "FATIGUE", "MALAISE", "ANOREXIA","LIVER BIG", "LIVER FIRM", "SPLEEN PALPABLE", "SPIDERS","ASCITES", "VARICES", "ALK PHOSPHATE","BILIRUBIN", "SGOT","ALBUMIN", "PROTIME", "HISTOLOGY"]
data = pd.read_csv('C:/Users/moizadamjee/Desktop/Uzair/hepatitas/hepatitis.csv')


# DATA CLEANING 

In [2]:
data.head()
df = data.coppy()

In [3]:
df['steroid'].fillna(df['steroid'].mode()[0], inplace = True)
df['fatigue'].fillna(df['fatigue'].mode()[0], inplace = True)
df['malaise'].fillna(df['malaise'].mode()[0], inplace = True)
df['anorexia'].fillna(df['anorexia'].mode()[0], inplace = True)
df['liver_big'].fillna(df['liver_big'].mode()[0], inplace = True)
df['liver_firm'].fillna(df['liver_firm'].mode()[0], inplace = True)
df['spleen_palpable'].fillna(df['spleen_palpable'].mode()[0], inplace = True)
df['spiders'].fillna(df['spiders'].mode()[0], inplace = True)
df['ascites'].fillna(df['ascites'].mode()[0], inplace = True)
df['varices'].fillna(df['varices'].mode()[0], inplace = True)

In [4]:
df['bilirubin'].fillna(df['bilirubin'].mean(), inplace = True)
df['alk_phosphate'].fillna(df['alk_phosphate'].mean(), inplace = True)
df['sgot'].fillna(df['sgot'].mean(), inplace = True)
df['protime'].fillna(df['protime'].mean(), inplace = True)
df['histology'].fillna(df['histology'].mode()[0], inplace = True)

In [5]:
df['albumin'].fillna(df['albumin'].mean(), inplace = True)

In [6]:
df.dtypes

age                  int64
sex                 object
steroid               bool
antivirals            bool
fatigue               bool
malaise               bool
anorexia              bool
liver_big             bool
liver_firm            bool
spleen_palpable       bool
spiders               bool
ascites               bool
varices               bool
bilirubin          float64
alk_phosphate      float64
sgot               float64
albumin            float64
protime            float64
histology             bool
class               object
dtype: object

In [7]:
df

age     sex  steroid  antivirals  fatigue  malaise  anorexia  liver_big  \
0     30    male    False       False    False    False     False      False   
1     50  female    False       False     True    False     False      False   
2     78  female     True       False     True    False     False       True   
3     31  female     True        True    False    False     False       True   
4     34  female     True       False    False    False     False       True   
5     34  female     True       False    False    False     False       True   
6     51  female    False       False     True    False      True       True   
7     23  female     True       False    False    False     False       True   
8     39  female     True       False     True    False     False       True   
9     30  female     True       False    False    False     False       True   
10    39  female    False        True    False    False     False      False   
11    32  female     True        True     True    False     False       True   
12    41  female     True        True     True    False     False       True   
13    30  female     True       False     True    False     False       True   
14    47  female    False        True    False    False     False       True   
15    38  female    False       False     True     True      True       True   
16    66  female     True       False     True    False     False       True   
17    40  female    False       False     True    False     False       True   
18    38  female     True       False    False    False     False       True   
19    38  female    False        True    False    False     False      False   
20    22    male     True        True     True    False     False       True   
21    27  female     True       False     True     True      True      False   
22    31  female     True       False    False    False     False       True   
23    42  female     True       False    False    False     False       True   
24    25    male    False        True    False    False     False       True   
25    27  female    False       False     True     True     False       True   
26    49  female    False        True     True     True      True       True   
27    58    male     True       False     True    False     False       True   
28    61  female    False       False     True    False     False      False   
29    51  female    False        True     True     True     False       True   
..   ...     ...      ...         ...      ...      ...       ...        ...   
125   34    male     True       False     True     True      True      False   
126   28  female     True       False     True     True      True       True   
127   50  female     True       False     True    False     False       True   
128   54  female    False       False     True     True     False       True   
129   57  female    False       False     True     True     False       True   
130   54  female     True       False    False    False     False       True   
131   31  female    False       False     True     True      True       True   
132   48  female     True       False     True     True      True       True   
133   72  female     True        True     True    False     False       True   
134   38  female    False       False    False    False     False       True   
135   25  female     True       False     True    False     False      False   
136   51  female     True       False    False    False     False      False   
137   38  female     True       False    False    False     False       True   
138   47  female     True       False     True     True     False       True   
139   45  female     True        True    False    False     False       True   
140   36  female    False       False     True     True      True      False   
141   54  female    False       False     True     True     False       True   
142   51  female     True       False     True    False     False       True   
143  

# DUMMY VALUES

In [8]:
data_new = pd.get_dummies(df, columns=['sex','steroid','antivirals','fatigue',
                                         'malaise','anorexia',
                                         'liver_big','liver_firm',
                                         'spleen_palpable','spiders',
                                         'ascites','varices','histology' ])

In [9]:
data_new.dtypes

age                        int64
bilirubin                float64
alk_phosphate            float64
sgot                     float64
albumin                  float64
protime                  float64
class                     object
sex_female                 uint8
sex_male                   uint8
steroid_False              uint8
steroid_True               uint8
antivirals_False           uint8
antivirals_True            uint8
fatigue_False              uint8
fatigue_True               uint8
malaise_False              uint8
malaise_True               uint8
anorexia_False             uint8
anorexia_True              uint8
liver_big_False            uint8
liver_big_True             uint8
liver_firm_False           uint8
liver_firm_True            uint8
spleen_palpable_False      uint8
spleen_palpable_True       uint8
spiders_False              uint8
spiders_True               uint8
ascites_False              uint8
ascites_True               uint8
varices_False              uint8
varices_Tr

In [10]:
data_y = pd.DataFrame(data_new['class'])
data_X = data_new.drop(['class'], axis=1)

# APPLYING MODEL SVM

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data_X, data_y, test_size=0.2)

In [12]:
from sklearn import metrics
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.svm import SVC, LinearSVC

models = (SVC(kernel='linear'),
          LinearSVC(),
          SVC(kernel='rbf'),
          SVC(kernel='poly'),
          SVC(kernel='sigmoid'))

for clf in models:
    print(clf)
    clf.fit(X_train,y_train)
    y_pred = clf.predict(X_test)
   
    print(metrics.accuracy_score(y_test, y_pred))

    print(confusion_matrix(y_test, y_pred))

    # New line
    print('\n')

    # Classification report
    print(classification_report(y_test,y_pred))

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)
0.9354838709677419
[[ 3  1]
 [ 1 26]]


             precision    recall  f1-score   support

        die       0.75      0.75      0.75         4
       live       0.96      0.96      0.96        27

avg / total       0.94      0.94      0.94        31

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)
0.9354838709677419
[[ 2  2]
 [ 0 27]]


             precision    recall  f1-score   support

        die       1.00      0.50      0.67         4
       live       0.93      1.00      0.96        27

avg / total       0.94      0.94      0.93        31

SVC(C=1.0, cache_size=200, class_weight=None, c

In [13]:
from sklearn import metrics
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.svm import SVC, LinearSVC

models = (SVC(kernel='linear',random_state=5,C=0.5,class_weight = "balanced"),
          LinearSVC(random_state=5,C=0.5,class_weight = "balanced"),
          SVC(kernel='rbf', random_state=5,C=0.5,class_weight = "balanced"),
          SVC(kernel='poly',random_state=5, C=0.5,class_weight = "balanced"),
          SVC(kernel='sigmoid',random_state=5,C=0.5,class_weight = "balanced"))

for clf in models:
    print(clf)
    clf.fit(X_train,y_train)
    y_pred = clf.predict(X_test)
    print(metrics.accuracy_score(y_test, y_pred))

    print(confusion_matrix(y_test, y_pred))

    # New line
    print('\n')

    # Classification report
    print(classification_report(y_test,y_pred))

SVC(C=0.5, cache_size=200, class_weight='balanced', coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=5, shrinking=True,
  tol=0.001, verbose=False)
0.9032258064516129
[[ 4  0]
 [ 3 24]]


             precision    recall  f1-score   support

        die       0.57      1.00      0.73         4
       live       1.00      0.89      0.94        27

avg / total       0.94      0.90      0.91        31

LinearSVC(C=0.5, class_weight='balanced', dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=5, tol=0.0001,
     verbose=0)
0.9354838709677419
[[ 3  1]
 [ 1 26]]


             precision    recall  f1-score   support

        die       0.75      0.75      0.75         4
       live       0.96      0.96      0.96        27

avg / total       0.94      0.94      0.94        31

SVC(C=0.5, cache_size=200, class_weight='

In [15]:
from sklearn import metrics
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.svm import SVC, LinearSVC

models = (SVC(kernel='linear',gamma=0.7),
          LinearSVC(C=0.5),
          SVC(kernel='rbf', gamma=0.7),
          SVC(kernel='poly', gamma=0.7),
         SVC(kernel='sigmoid', gamma=0.7))

for clf in models:
    print(clf)
    clf.fit(X_train,y_train)
    y_pred = clf.predict(X_test)
    print(metrics.accuracy_score(y_test, y_pred))

    print(confusion_matrix(y_test, y_pred))

    # New line
    print('\n')

    # Classification report
    print(classification_report(y_test,y_pred))

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.7, kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)
0.9354838709677419
[[ 3  1]
 [ 1 26]]


             precision    recall  f1-score   support

        die       0.75      0.75      0.75         4
       live       0.96      0.96      0.96        27

avg / total       0.94      0.94      0.94        31

LinearSVC(C=0.5, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)
0.8064516129032258
[[ 4  0]
 [ 6 21]]


             precision    recall  f1-score   support

        die       0.40      1.00      0.57         4
       live       1.00      0.78      0.88        27

avg / total       0.92      0.81      0.84        31

SVC(C=1.0, cache_size=200, class_weight=None, coef

In [16]:
from sklearn import metrics
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.svm import SVC, LinearSVC

models = (SVC(kernel='linear', tol=0.1,class_weight = "balanced"),
          LinearSVC(tol=0.1,class_weight = "balanced"),
          SVC(kernel='rbf', tol=0.1,class_weight = "balanced"),
          SVC(kernel='poly',tol=0.1,class_weight = "balanced"),
          SVC(kernel='sigmoid',tol=0.1,class_weight = "balanced"))

for clf in models:
    print(clf)
    clf.fit(X_train,y_train)
    y_pred = clf.predict(X_test)
    print(metrics.accuracy_score(y_test, y_pred))

    print(confusion_matrix(y_test, y_pred))

    # New line
    print('\n')

    # Classification report
    print(classification_report(y_test,y_pred))

SVC(C=1.0, cache_size=200, class_weight='balanced', coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.1, verbose=False)
0.9032258064516129
[[ 4  0]
 [ 3 24]]


             precision    recall  f1-score   support

        die       0.57      1.00      0.73         4
       live       1.00      0.89      0.94        27

avg / total       0.94      0.90      0.91        31

LinearSVC(C=1.0, class_weight='balanced', dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.1,
     verbose=0)
0.9032258064516129
[[ 3  1]
 [ 2 25]]


             precision    recall  f1-score   support

        die       0.60      0.75      0.67         4
       live       0.96      0.93      0.94        27

avg / total       0.91      0.90      0.91        31

SVC(C=1.0, cache_size=200, class_weight=

# USING DROPNA():

In [28]:
test_df = data

In [29]:
test_df = test_df.dropna()
data_d = pd.get_dummies(test_df)

In [30]:
data_d.dtypes

age                        int64
antivirals                  bool
bilirubin                float64
alk_phosphate            float64
sgot                     float64
albumin                  float64
protime                  float64
histology                   bool
sex_female                 uint8
sex_male                   uint8
steroid_False              uint8
steroid_True               uint8
fatigue_False              uint8
fatigue_True               uint8
malaise_False              uint8
malaise_True               uint8
anorexia_False             uint8
anorexia_True              uint8
liver_big_False            uint8
liver_big_True             uint8
liver_firm_False           uint8
liver_firm_True            uint8
spleen_palpable_False      uint8
spleen_palpable_True       uint8
spiders_False              uint8
spiders_True               uint8
ascites_False              uint8
ascites_True               uint8
varices_False              uint8
varices_True               uint8
class_die 

# APPYING MODEL ON ONLY (TYPE WHICH ARE BOOL & OBJECT)

In [31]:
import numpy as np

x = data_d.loc[:, 'age':'varices_True'].values 
output_data = test_df['class']
output_data = output_data.values
y = [1 if i == 'live' else -1 for i in output_data] 


In [32]:
x.shape

(80, 30)

In [33]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=2)


In [34]:
from sklearn import metrics
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.svm import SVC, LinearSVC

models = (SVC(kernel='linear'),
          LinearSVC(),
          SVC(kernel='rbf'),
          SVC(kernel='poly'),
          SVC(kernel='sigmoid'))

for clf in models:
    print(clf)
    clf.fit(X_train,y_train)
    y_pred = clf.predict(X_test)
    print(metrics.accuracy_score(y_test, y_pred))

    print(confusion_matrix(y_test, y_pred))

    # New line
    print('\n')

    # Classification report
    print(classification_report(y_test,y_pred))

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)
0.8125
[[ 3  1]
 [ 2 10]]


             precision    recall  f1-score   support

         -1       0.60      0.75      0.67         4
          1       0.91      0.83      0.87        12

avg / total       0.83      0.81      0.82        16

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)
0.8125
[[ 1  3]
 [ 0 12]]


             precision    recall  f1-score   support

         -1       1.00      0.25      0.40         4
          1       0.80      1.00      0.89        12

avg / total       0.85      0.81      0.77        16

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_fun

In [35]:
from sklearn import metrics
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.svm import SVC, LinearSVC

models = (SVC(kernel='linear',random_state=5),
          LinearSVC(random_state=5),
          SVC(kernel='rbf', random_state=5),
          SVC(kernel='poly',random_state=5, degree=3),
          SVC(kernel='sigmoid',random_state=5))

for clf in models:
    print(clf)
    clf.fit(X_train,y_train)
    y_pred = clf.predict(X_test)
    print(metrics.accuracy_score(y_test, y_pred))

    print(confusion_matrix(y_test, y_pred))

    # New line
    print('\n')

    # Classification report
    print(classification_report(y_test,y_pred))

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=5, shrinking=True,
  tol=0.001, verbose=False)
0.8125
[[ 3  1]
 [ 2 10]]


             precision    recall  f1-score   support

         -1       0.60      0.75      0.67         4
          1       0.91      0.83      0.87        12

avg / total       0.83      0.81      0.82        16

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=5, tol=0.0001,
     verbose=0)
0.75
[[ 0  4]
 [ 0 12]]


             precision    recall  f1-score   support

         -1       0.00      0.00      0.00         4
          1       0.75      1.00      0.86        12

avg / total       0.56      0.75      0.64        16

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_sh

In [36]:
from sklearn import metrics
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.svm import SVC, LinearSVC

models = (SVC(kernel='linear', C=0.1),
          LinearSVC(C=0.1),
          SVC(kernel='rbf', C=0.1),
          SVC(kernel='poly', C=0.1),
         SVC(kernel='sigmoid', C=0.1))

for clf in models:
    print(clf)
    clf.fit(X_train,y_train)
    y_pred = clf.predict(X_test)
    print(metrics.accuracy_score(y_test, y_pred))

    print(confusion_matrix(y_test, y_pred))

    # New line
    print('\n')

    # Classification report
    print(classification_report(y_test,y_pred))

SVC(C=0.1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)
0.8125
[[ 1  3]
 [ 0 12]]


             precision    recall  f1-score   support

         -1       1.00      0.25      0.40         4
          1       0.80      1.00      0.89        12

avg / total       0.85      0.81      0.77        16

LinearSVC(C=0.1, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)
0.6875
[[3 1]
 [4 8]]


             precision    recall  f1-score   support

         -1       0.43      0.75      0.55         4
          1       0.89      0.67      0.76        12

avg / total       0.77      0.69      0.71        16

SVC(C=0.1, cache_size=200, class_weight=None, coef0=0.0,
  decision_functio

In [39]:
from sklearn import metrics
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.svm import SVC, LinearSVC

models = (SVC(kernel='linear',gamma=0.7),
          LinearSVC(C=0.5),
          SVC(kernel='rbf', gamma=0.7),
          SVC(kernel='poly', gamma=0.7),
         SVC(kernel='sigmoid', gamma=0.7))

for clf in models:
    print(clf)
    clf.fit(X_train,y_train)
    y_pred = clf.predict(X_test)
    print(metrics.accuracy_score(y_test, y_pred))

    print(confusion_matrix(y_test, y_pred))

    # New line
    print('\n')

    # Classification report
    print(classification_report(y_test,y_pred))

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.7, kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)
0.8125
[[ 3  1]
 [ 2 10]]


             precision    recall  f1-score   support

         -1       0.60      0.75      0.67         4
          1       0.91      0.83      0.87        12

avg / total       0.83      0.81      0.82        16

LinearSVC(C=0.5, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)
0.8125
[[ 3  1]
 [ 2 10]]


             precision    recall  f1-score   support

         -1       0.60      0.75      0.67         4
          1       0.91      0.83      0.87        12

avg / total       0.83      0.81      0.82        16

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_functi

# APPYING MODEL AFTER USING DROPNA() METHOD

In [40]:

data_d.dtypes

age                        int64
antivirals                  bool
bilirubin                float64
alk_phosphate            float64
sgot                     float64
albumin                  float64
protime                  float64
histology                   bool
sex_female                 uint8
sex_male                   uint8
steroid_False              uint8
steroid_True               uint8
fatigue_False              uint8
fatigue_True               uint8
malaise_False              uint8
malaise_True               uint8
anorexia_False             uint8
anorexia_True              uint8
liver_big_False            uint8
liver_big_True             uint8
liver_firm_False           uint8
liver_firm_True            uint8
spleen_palpable_False      uint8
spleen_palpable_True       uint8
spiders_False              uint8
spiders_True               uint8
ascites_False              uint8
ascites_True               uint8
varices_False              uint8
varices_True               uint8
class_die 

In [41]:
import numpy as np

x = data_d.loc[:, 'age':].values 
output_data = test_df['class']
output_data = output_data.values
y = [1 if i == 'live' else -1 for i in output_data] 



In [43]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=2)


In [44]:
from sklearn import metrics
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.svm import SVC, LinearSVC

models = (SVC(kernel='linear'),
          LinearSVC(),
          SVC(kernel='rbf'),
          SVC(kernel='poly'),
          SVC(kernel='sigmoid'))

for clf in models:
    print(clf)
    clf.fit(X_train,y_train)
    y_pred = clf.predict(X_test)
    print(metrics.accuracy_score(y_test, y_pred))

    print(confusion_matrix(y_test, y_pred))

    # New line
    print('\n')

    # Classification report
    print(classification_report(y_test,y_pred))

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)
1.0
[[ 4  0]
 [ 0 12]]


             precision    recall  f1-score   support

         -1       1.00      1.00      1.00         4
          1       1.00      1.00      1.00        12

avg / total       1.00      1.00      1.00        16

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)
0.9375
[[ 3  1]
 [ 0 12]]


             precision    recall  f1-score   support

         -1       1.00      0.75      0.86         4
          1       0.92      1.00      0.96        12

avg / total       0.94      0.94      0.93        16

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_functi

In [45]:
from sklearn import metrics
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.svm import SVC, LinearSVC

models = (SVC(kernel='linear',random_state=5),
          LinearSVC(random_state=5),
          SVC(kernel='rbf', random_state=5),
          SVC(kernel='poly',random_state=5, degree=3),
          SVC(kernel='sigmoid',random_state=5))

for clf in models:
    print(clf)
    clf.fit(X_train,y_train)
    y_pred = clf.predict(X_test)
    print(metrics.accuracy_score(y_test, y_pred))

    print(confusion_matrix(y_test, y_pred))

    # New line
    print('\n')

    # Classification report
    print(classification_report(y_test,y_pred))

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=5, shrinking=True,
  tol=0.001, verbose=False)
1.0
[[ 4  0]
 [ 0 12]]


             precision    recall  f1-score   support

         -1       1.00      1.00      1.00         4
          1       1.00      1.00      1.00        12

avg / total       1.00      1.00      1.00        16

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=5, tol=0.0001,
     verbose=0)
0.9375
[[ 3  1]
 [ 0 12]]


             precision    recall  f1-score   support

         -1       1.00      0.75      0.86         4
          1       0.92      1.00      0.96        12

avg / total       0.94      0.94      0.93        16

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_sha

In [46]:
from sklearn import metrics
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.svm import SVC, LinearSVC

models = (SVC(kernel='linear', C=0.1),
          LinearSVC(C=0.1),
          SVC(kernel='rbf', C=0.1),
          SVC(kernel='poly', C=0.1),
         SVC(kernel='sigmoid', C=0.1))

for clf in models:
    print(clf)
    clf.fit(X_train,y_train)
    y_pred = clf.predict(X_test)
    print(metrics.accuracy_score(y_test, y_pred))

    print(confusion_matrix(y_test, y_pred))

    # New line
    print('\n')

    # Classification report
    print(classification_report(y_test,y_pred))

SVC(C=0.1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)
0.9375
[[ 3  1]
 [ 0 12]]


             precision    recall  f1-score   support

         -1       1.00      0.75      0.86         4
          1       0.92      1.00      0.96        12

avg / total       0.94      0.94      0.93        16

LinearSVC(C=0.1, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)
0.875
[[ 3  1]
 [ 1 11]]


             precision    recall  f1-score   support

         -1       0.75      0.75      0.75         4
          1       0.92      0.92      0.92        12

avg / total       0.88      0.88      0.88        16

SVC(C=0.1, cache_size=200, class_weight=None, coef0=0.0,
  decision_func

In [48]:
from sklearn import metrics
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.svm import SVC, LinearSVC

models = (SVC(kernel='linear',gamma=0.7),
          LinearSVC(C=0.5),
          SVC(kernel='rbf', gamma=0.7),
          SVC(kernel='poly', gamma=0.7),
         SVC(kernel='sigmoid', gamma=0.7))

for clf in models:
    print(clf)
    clf.fit(X_train,y_train)
    y_pred = clf.predict(X_test)
    print(metrics.accuracy_score(y_test, y_pred))

    print(confusion_matrix(y_test, y_pred))

    # New line
    print('\n')

    # Classification report
    print(classification_report(y_test,y_pred))

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.7, kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)
1.0
[[ 4  0]
 [ 0 12]]


             precision    recall  f1-score   support

         -1       1.00      1.00      1.00         4
          1       1.00      1.00      1.00        12

avg / total       1.00      1.00      1.00        16

LinearSVC(C=0.5, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)
0.9375
[[ 3  1]
 [ 0 12]]


             precision    recall  f1-score   support

         -1       1.00      0.75      0.86         4
          1       0.92      1.00      0.96        12

avg / total       0.94      0.94      0.93        16

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_

In [14]:
import warnings
warnings.filterwarnings('ignore')
import numpy as np
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.model_selection import GridSearchCV
#C_range = (np.logspace(-2, 10, 13))
#gamma_range = np.logspace(-9, 3, 13)
C_range = np.arange(0.1,2.5,0.1)
gamma_range = np.arange(0.1,1,0.1) 
#print(C_range)
#print(gamma_range)
param_grid = dict(gamma=gamma_range, C=C_range)
cv = StratifiedShuffleSplit(n_splits=5, test_size=0.2)
grid = GridSearchCV(SVC(kernel='linear'), param_grid=param_grid, cv=cv)
grid.fit(X_train, y_train)

print("The best parameters are %s with a score of %0.2f"
      % (grid.best_params_, grid.best_score_))

grid = GridSearchCV(SVC(kernel='rbf'), param_grid=param_grid, cv=cv)
grid.fit(X_train, y_train)

print("The best parameters are %s with a score of %0.2f"
      % (grid.best_params_, grid.best_score_))

grid = GridSearchCV(SVC(kernel='poly'), param_grid=param_grid, cv=cv)
grid.fit(X_train, y_train)

print("The best parameters are %s with a score of %0.2f"
      % (grid.best_params_, grid.best_score_))

grid = GridSearchCV(SVC(kernel='sigmoid'), param_grid=param_grid, cv=cv)
grid.fit(X_train, y_train)

print("The best parameters are %s with a score of %0.2f"
      % (grid.best_params_, grid.best_score_))


The best parameters are {'C': 0.1, 'gamma': 0.1} with a score of 0.83
The best parameters are {'C': 0.1, 'gamma': 0.1} with a score of 0.80
The best parameters are {'C': 0.1, 'gamma': 0.1} with a score of 0.75
The best parameters are {'C': 0.1, 'gamma': 0.1} with a score of 0.80


In [15]:
from sklearn import metrics
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.svm import SVC, LinearSVC

models = ( (SVC(kernel='linear', C=0.1,gamma=0.1),
          SVC(kernel='rbf', C=0.1,gamma=0.1),
          SVC(kernel='poly', C=0.1,gamma=0.1),
         SVC(kernel='sigmoid', C=0.1,gamma=0.1)))

for clf in models:
    print(clf)
    clf.fit(X_train,y_train)
    y_pred = clf.predict(X_test)
    print(metrics.accuracy_score(y_test, y_pred))

    print(confusion_matrix(y_test, y_pred))

    # New line
    print('\n')

    # Classification report
    print(classification_report(y_test,y_pred))

SVC(C=0.1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.1, kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)
0.8387096774193549
[[ 3  4]
 [ 1 23]]


             precision    recall  f1-score   support

        die       0.75      0.43      0.55         7
       live       0.85      0.96      0.90        24

avg / total       0.83      0.84      0.82        31

SVC(C=0.1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.1, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)
0.7741935483870968
[[ 0  7]
 [ 0 24]]


             precision    recall  f1-score   support

        die       0.00      0.00      0.00         7
       live       0.77      1.00      0.87        24

avg / total       0.60      0.77      0.68        31

SVC(C=0.1, cache_size=200, class_weight=Non